/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
 * Address of the Clock control register (AHB1ENR):
 * 0x4002 3800 + 0x30 = 0x40023830
 * Address of the GPIOD mode register (use to control mode I/O):
 * 0x4002 0C00 + 0x00 = 0x40020C00
 * Address of GPIOD output data register (use to write):
 * 0x4002 0C00 + 0x14 = 0x40020C04
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "main.h"

int main(void)
{
	/*
	uint32_t *pCCR = (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortOutReg = (uint32_t*)0x40020C14;
	*/

	RCC_AHB1ENR_t volatile *const pCCR 		= (RCC_AHB1ENR_t*)0x40023830;
	GPIOx_ODR_t volatile *const pPortDModeReg 	= (GPIOx_ODR_t*)0x40020C00;
	GPIOx_MODE_t volatile *const pPortOutReg 	= (GPIOx_MODE_t*)0x40020C14;

	//1. Enable the clock for GPIOD peripheral in the AH1ENR (SET the 3rd bit position)
	//*pCCR |= 0x08;
	//*pCCR |= (1 << 3);
	pCCR->gpiod_en = 1;

	//2. Configure the mode of the IO 12 pin as output.
	//a. Clear the 24 and 25th bit position (CLEAR)
	//*pPortDModeReg &= 0xFCFFFFFF;
	//*pPortDModeReg &= ~(3 << 24);
	pPortDModeReg->pin_12 = 1;

	while(1)
	{
		//Set 12th bit of the output data register to make I/O pin-12 as HIGH
		pPortDOutReg->pin_12  = 1;

		//introduce small human observable delay
		//This loop executes for 300K times
		for(uint32_t i=0 ; i < 300000 ; i++ );

		//Reset 12th bit of the output data register to make I/O pin-12 as LOW
		pPortDOutReg->pin_12  = 0;

		for(uint32_t i=0 ; i < 300000 ; i++ );
	}

	for(;;);

}
